name: Build and Package WAR

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs for the workflow
jobs:
  build:
    # The operating system to use
    runs-on: ubuntu-latest

    # Steps to execute
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11 (or whatever version you're using)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt' 

      # Cache Maven dependencies to speed up build
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project with Maven and package it as a WAR file
      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      # Upload the WAR file as an artifact (Optional)
      - name: Upload WAR file
        uses: actions/upload-artifact@v3
        with:
          name: application-war
          path: target/*.war
