name: Build and Package WAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps to execute
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt' 

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project with Maven and package it as a WAR file
      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      # Notify Jenkins on successful completion
      - name: Notify Jenkins on Success
        if: ${{ success() }}
        run: |
          curl -X POST https://6866-103-139-5-226.ngrok-free.app//job/InssuredAssurance-Deployment-Pipeline/build?token=${{ secrets.JENKINS_TOKEN }} \
               -H 'Jenkins-Crumb: ${{ secrets.JENKINS_CRUMB }}' \
               -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}
